// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:37.174Z"

// transferhistory/src/interfaces/dummy.mts
export function dummy(n) {
    return '';
}
