// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:47.816Z"

// transferhistory/src/interfaces/foo/bar.mts
export function dummy(n) {
    return '';
}
