// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:43.375Z"

// transferhistory/src/routes/api/v1/health/upstreams/[backend].mts
export function get() {
    return '';
}
