// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:47.817Z"

// transferhistory/src/routes/api/v1/status/upstreams/[backend].mts
export function get() {
    return '';
}
