// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:41.238Z"

// transferhistory/src/providers/foo/bar.mts
export function dummy(n) {
    return '';
}
