// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:45.533Z"

// transferhistory/src/routes/api/v1/status/upstreams.mts
export function get() {
    return '';
}
