// DO NOT EDIT THIS FILE BY HAND
// YOUR CHANGES WILL BE OVERWRITTEN
// @generated  "2022-04-08T18:59:42.301Z"

// transferhistory/src/routes/api/v1/health/index.mts
export function get() {
    return '';
}
